### ISSUE TITLE
Consider External Operators for Peripheral Services

### ISSUE THREAD

**Issue by dmlb2000** [geerlingguy/drupal-operator#15]
Drupal depends on a lot of external processes which already have their life-cycle managed by operators. Strategy should be worked around whether or not to integrate with those operators or re-implement the life-cycle management of those peripheral services in here.

 * MySQL - https://vitess.io/
 * Redis - https://github.com/spotahome/redis-operator
 * Solr - https://github.com/bloomberg/solr-operator
 * Elasticsearch - https://github.com/zalando-incubator/es-operator
 * Memcached - https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator

There maybe others but this is a short list.

**Comment by geerlingguy** [comment]
I'm also working on a MariaDB operator to pair up with this one: https://github.com/geerlingguy/mariadb-operator

**Comment by geerlingguy** [comment]
See this example, using Drupal and MySQL: https://github.com/geerlingguy/ansible-for-kubernetes/tree/master/operators-drupal-mariadb

**Comment by dmlb2000** [comment]
Is there a PostgreSQL operator that is working yet for this?

**Comment by geerlingguy** [comment]
@dmlb2000 - A couple popular ones I've found:

  - https://github.com/zalando/postgres-operator
  - https://github.com/CrunchyData/postgres-operator

**Comment by dmlb2000** [comment]
@geerlingguy do you know if they have HA configurations? I was looking at Patroni as an alternative.

**Comment by geerlingguy** [comment]
Not sure, you'd have to dig into those operators. So far I've only done Postgres inside Kubernetes once, so my experience there is a lot shallower than with MySQL/MariaDB.

**Comment by dmlb2000** [comment]
https://github.com/zalando/patroni for reference

**Comment by kfox1111** [comment]
It would be great if these operators or choices were made to use the operators that were part of operatorhub.io. When using the OLM to install the operators, I believe it should handle operators that depend on other operators.
