### ISSUE TITLE
Allowing Drush from outside the cluster

### ISSUE THREAD

**Issue by dmlb2000** [geerlingguy/drupal-operator#16]
Many Drupal deployments require the use of Drush aliases to access code and files remotely. Should an `sshd` service side car be used to allow external access to code and files?

Eash `sshd` would be bound to the PV not to the running web server.

Kinda defeats the way k8s scales services.

There's lots of discussion around this just putting in the issue.

**Comment by geerlingguy** [comment]
Yeah, that's something I'm loathe to do—if you're going to go into Kubernetes, better (IMO) to ditch the idea of running SSH entirely. Instead, you'd want tooling to be able to run drush commands some other way.

It would be nice if Drush had an HTTP API, too... that way you could run Drush as a service for your site :)

**Comment by geerlingguy** [comment]
Possibly related: https://github.com/drush-ops/drush/issues/9

**Comment by dmlb2000** [comment]
Crazy thought, could you write a plugin for https://cockpit-project.org/ to understand drush?

**Comment by thomscode** [comment]
Given what is in [consolidation/site-process](https://github.com/consolidation/site-process/tree/master/src/Transport) for transports, it probably wouldn't be difficult to create a `kubectl` transport. Just needs someone with an example to work with and time to experiment.

**Comment by kfox1111** [comment]
simply kubectl exec'ing and running drush commands works.

But, a kubernetes job may be another way to do it. Possibly a custom drushJob CRD could be created to create the jobs for us.

**Comment by geerlingguy** [comment]
I think for this operator in particular, I don't want to try to solve this issue as there's no simple way to do it without building some sort of SSH support into Kubernetes, which is a feature that would be wrought with trouble and caveats.

If someone else figures out a simple way to allow Drush integration outside the cluster that could be plugged into this operator, I'd entertain adding it.

**Comment by geerlingguy** [comment]
Oops, didn't mean to reopen...

**Comment by kfox1111** [comment]
See my comment from above. Maybe there can be a Kubernetes object to run a DrushJob?
