### ISSUE TITLE
Allow use of secret for database password

### ISSUE THREAD

**Issue by kfox1111** [geerlingguy/drupal-operator#22]
The example CR has the password in the CR
  database_password: change-me

CR's do not support encryption in the kubernetes apiserver, while secrets do.
It would be good if passwords could be placed in a secret and referenced in the CR.

**Comment by geerlingguy** [comment]
I agree; I also have semi-related issue #4.

**Comment by dmlb2000** [comment]
I know a lot of folks like to use the `.env` environment variable approach to managing configuration in different environments. K8S can store secrets in environment variables, should I put in a pull request to handle that?
