### ISSUE TITLE
Set $settings['config_sync_directory'] in settings configmap

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-operator#25]
I get the following error with new sites installed using the config from this operator:

<img width="1221" alt="Screen Shot 2020-05-24 at 6 14 26 PM" src="https://user-images.githubusercontent.com/481677/82767108-7c355700-9dea-11ea-9aaf-1e1d790375ba.png">

> Your `sites/default/settings.php` file must define the `$settings['config_sync_directory']` setting as a string containing the directory in which configuration files can be found.

This should be added, defaulting to whatever Drupal defaults to.

**Comment by geerlingguy** [comment]
Drupal defaults to something like:

```php
<?php
$settings['config_sync_directory'] = 'sites/default/files/config_[hash goes here]';
```

So... that's not super secure. But at least it would work in a new install. I tested `sites/default/sync` but that gave permissions warnings on a fresh installation... you'd have to configure a separate volume/mount for that directory if you wanted it to actually work :(

**Comment by zar-wtag** [comment]
I recently tried to upgrade one of our projects from D8.9.13 to D9 and after upgrading I needed to run `drush updb` I got the following error.
```
In FileStorageFactory.php line 26:
                                                                               
  The config sync directory is not defined in $settings["config_sync_director  
  y"]                                                                          
```

I believe it is the same as original poster. Any fix to this yet?

**Comment by oadekoya12** [comment]
> Drupal defaults to something like:
> 
> ```
> <?php
> $settings['config_sync_directory'] = 'sites/default/files/config_[hash goes here]';
> ```
> 
> So... that's not super secure. But at least it would work in a new install. I tested `sites/default/sync` but that gave permissions warnings on a fresh installation... you'd have to configure a separate volume/mount for that directory if you wanted it to actually work :(

I have tried the configuration setting in the settings file and ran Drush cr and Drush cron. But am still have the same error showing up on the status page.
